version: '3.4'

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_sequelize
  server:
    image: detteksie/blog-sequelize
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DEBUG: blog-sequelize:*
      JWT_SECRET: H3ll0W0rld!
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog_sequelize
    ports:
      - 4000:4000

volumes:
  data:
